# Generated by Django 3.1.12 on 2025-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250712_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(default='TEMP', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, upload_to='service_icons/'),
        ),
    ]
