# Generated by Django 3.1.12 on 2025-07-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250712_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
